// Sample car data for seeding and auto-updating
export interface CarData {
  brand: string;
  model: string;
  type: string;
  year: number;
  engine?: string;
  fuelType?: string;
  transmission?: string;
  horsepower?: number;
  torque?: number;
  drivetrain?: string;
  seatingCapacity?: number;
  price?: number;
  imageUrl?: string;
  color?: string;
  bodyStyle?: string;
  mpgCity?: number;
  mpgHighway?: number;
}

export const SAMPLE_CAR_DATA: CarData[] = [
  {
    brand: "Toyota",
    model: "Camry",
    type: "Sedan",
    year: 2025,
    engine: "2.5L 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 203,
    torque: 184,
    drivetrain: "FWD",
    seatingCapacity: 5,
    price: 28400,
    color: "Pearl White",
    bodyStyle: "4-Door",
    mpgCity: 28,
    mpgHighway: 39,
  },
  {
    brand: "Toyota",
    model: "RAV4",
    type: "SUV",
    year: 2025,
    engine: "2.5L 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 203,
    torque: 184,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 32450,
    color: "Blueprint",
    bodyStyle: "5-Door",
    mpgCity: 27,
    mpgHighway: 35,
  },
  {
    brand: "Toyota",
    model: "Corolla",
    type: "Sedan",
    year: 2025,
    engine: "2.0L 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "CVT",
    horsepower: 169,
    torque: 151,
    drivetrain: "FWD",
    seatingCapacity: 5,
    price: 22850,
    color: "Classic Silver",
    bodyStyle: "4-Door",
    mpgCity: 32,
    mpgHighway: 41,
  },
  {
    brand: "Honda",
    model: "Civic",
    type: "Sedan",
    year: 2025,
    engine: "2.0L 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "CVT",
    horsepower: 158,
    torque: 138,
    drivetrain: "FWD",
    seatingCapacity: 5,
    price: 24950,
    color: "Rallye Red",
    bodyStyle: "4-Door",
    mpgCity: 33,
    mpgHighway: 42,
  },
  {
    brand: "Honda",
    model: "CR-V",
    type: "SUV",
    year: 2025,
    engine: "1.5L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "CVT",
    horsepower: 190,
    torque: 179,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 33750,
    color: "Canyon River Blue",
    bodyStyle: "5-Door",
    mpgCity: 28,
    mpgHighway: 34,
  },
  {
    brand: "Honda",
    model: "Accord",
    type: "Sedan",
    year: 2025,
    engine: "1.5L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "CVT",
    horsepower: 192,
    torque: 192,
    drivetrain: "FWD",
    seatingCapacity: 5,
    price: 28990,
    color: "Platinum White",
    bodyStyle: "4-Door",
    mpgCity: 30,
    mpgHighway: 37,
  },
  {
    brand: "Ford",
    model: "F-150",
    type: "Truck",
    year: 2025,
    engine: "3.5L V6 EcoBoost",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 400,
    torque: 500,
    drivetrain: "4WD",
    seatingCapacity: 5,
    price: 41990,
    color: "Antimatter Blue",
    bodyStyle: "Crew Cab",
    mpgCity: 20,
    mpgHighway: 26,
  },
  {
    brand: "Ford",
    model: "Mustang",
    type: "Coupe",
    year: 2025,
    engine: "5.0L V8",
    fuelType: "Gasoline",
    transmission: "Manual",
    horsepower: 480,
    torque: 415,
    drivetrain: "RWD",
    seatingCapacity: 4,
    price: 42990,
    color: "Vapor Blue",
    bodyStyle: "2-Door",
    mpgCity: 16,
    mpgHighway: 25,
  },
  {
    brand: "Ford",
    model: "Explorer",
    type: "SUV",
    year: 2025,
    engine: "2.3L EcoBoost 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 300,
    torque: 310,
    drivetrain: "AWD",
    seatingCapacity: 7,
    price: 38990,
    color: "Stone Gray",
    bodyStyle: "5-Door",
    mpgCity: 24,
    mpgHighway: 30,
  },
  {
    brand: "BMW",
    model: "3 Series",
    type: "Sedan",
    year: 2025,
    engine: "2.0L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 255,
    torque: 295,
    drivetrain: "RWD",
    seatingCapacity: 5,
    price: 44900,
    color: "Alpine White",
    bodyStyle: "4-Door",
    mpgCity: 26,
    mpgHighway: 36,
  },
  {
    brand: "BMW",
    model: "X5",
    type: "SUV",
    year: 2025,
    engine: "3.0L Turbo 6-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 375,
    torque: 383,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 65900,
    color: "Carbon Black",
    bodyStyle: "5-Door",
    mpgCity: 23,
    mpgHighway: 29,
  },
  {
    brand: "Mercedes-Benz",
    model: "C-Class",
    type: "Sedan",
    year: 2025,
    engine: "2.0L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 255,
    torque: 295,
    drivetrain: "RWD",
    seatingCapacity: 5,
    price: 47500,
    color: "Polar White",
    bodyStyle: "4-Door",
    mpgCity: 25,
    mpgHighway: 35,
  },
  {
    brand: "Mercedes-Benz",
    model: "GLE",
    type: "SUV",
    year: 2025,
    engine: "2.0L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 255,
    torque: 273,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 62900,
    color: "Obsidian Black",
    bodyStyle: "5-Door",
    mpgCity: 22,
    mpgHighway: 29,
  },
  {
    brand: "Tesla",
    model: "Model 3",
    type: "Sedan",
    year: 2025,
    engine: "Dual Motor Electric",
    fuelType: "Electric",
    transmission: "Automatic",
    horsepower: 346,
    torque: 376,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 42990,
    color: "Midnight Silver",
    bodyStyle: "4-Door",
    mpgCity: 132,
    mpgHighway: 0,
  },
  {
    brand: "Tesla",
    model: "Model Y",
    type: "SUV",
    year: 2025,
    engine: "Dual Motor Electric",
    fuelType: "Electric",
    transmission: "Automatic",
    horsepower: 384,
    torque: 376,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 47990,
    color: "Pearl White",
    bodyStyle: "5-Door",
    mpgCity: 127,
    mpgHighway: 0,
  },
  {
    brand: "Chevrolet",
    model: "Silverado 1500",
    type: "Truck",
    year: 2025,
    engine: "5.3L V8",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 355,
    torque: 383,
    drivetrain: "4WD",
    seatingCapacity: 5,
    price: 39900,
    color: "Northsky Blue",
    bodyStyle: "Crew Cab",
    mpgCity: 18,
    mpgHighway: 24,
  },
  {
    brand: "Chevrolet",
    model: "Equinox",
    type: "SUV",
    year: 2025,
    engine: "1.5L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 175,
    torque: 203,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 28600,
    color: "Iridescent Pearl",
    bodyStyle: "5-Door",
    mpgCity: 26,
    mpgHighway: 31,
  },
  {
    brand: "Hyundai",
    model: "Tucson",
    type: "SUV",
    year: 2025,
    engine: "2.5L 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 187,
    torque: 178,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 30550,
    color: "Amazon Gray",
    bodyStyle: "5-Door",
    mpgCity: 26,
    mpgHighway: 33,
  },
  {
    brand: "Hyundai",
    model: "Elantra",
    type: "Sedan",
    year: 2025,
    engine: "2.0L 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "CVT",
    horsepower: 147,
    torque: 132,
    drivetrain: "FWD",
    seatingCapacity: 5,
    price: 22750,
    color: "Ecotronic Gray",
    bodyStyle: "4-Door",
    mpgCity: 33,
    mpgHighway: 42,
  },
  {
    brand: "Volkswagen",
    model: "Golf GTI",
    type: "Hatchback",
    year: 2025,
    engine: "2.0L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Manual",
    horsepower: 241,
    torque: 273,
    drivetrain: "FWD",
    seatingCapacity: 5,
    price: 32890,
    color: "Kings Red",
    bodyStyle: "5-Door",
    mpgCity: 25,
    mpgHighway: 34,
  },
  {
    brand: "Volkswagen",
    model: "Tiguan",
    type: "SUV",
    year: 2025,
    engine: "2.0L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 184,
    torque: 221,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 33990,
    color: "Oryx White",
    bodyStyle: "5-Door",
    mpgCity: 24,
    mpgHighway: 31,
  },
  {
    brand: "Audi",
    model: "A4",
    type: "Sedan",
    year: 2025,
    engine: "2.0L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 261,
    torque: 273,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 45900,
    color: "Navarra Blue",
    bodyStyle: "4-Door",
    mpgCity: 27,
    mpgHighway: 35,
  },
  {
    brand: "Audi",
    model: "Q5",
    type: "SUV",
    year: 2025,
    engine: "2.0L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 261,
    torque: 273,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 49900,
    color: "Glacier White",
    bodyStyle: "5-Door",
    mpgCity: 24,
    mpgHighway: 30,
  },
  {
    brand: "Nissan",
    model: "Altima",
    type: "Sedan",
    year: 2025,
    engine: "2.5L 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "CVT",
    horsepower: 188,
    torque: 180,
    drivetrain: "FWD",
    seatingCapacity: 5,
    price: 26590,
    color: "Gun Metallic",
    bodyStyle: "4-Door",
    mpgCity: 28,
    mpgHighway: 39,
  },
  {
    brand: "Nissan",
    model: "Rogue",
    type: "SUV",
    year: 2025,
    engine: "1.5L Turbo 3-Cylinder",
    fuelType: "Gasoline",
    transmission: "CVT",
    horsepower: 201,
    torque: 225,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 30990,
    color: "Boulder Gray",
    bodyStyle: "5-Door",
    mpgCity: 30,
    mpgHighway: 37,
  },
  {
    brand: "Mazda",
    model: "CX-5",
    type: "SUV",
    year: 2025,
    engine: "2.5L 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 187,
    torque: 186,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 30750,
    color: "Soul Red Crystal",
    bodyStyle: "5-Door",
    mpgCity: 25,
    mpgHighway: 31,
  },
  {
    brand: "Mazda",
    model: "MX-5 Miata",
    type: "Convertible",
    year: 2025,
    engine: "2.0L 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Manual",
    horsepower: 181,
    torque: 151,
    drivetrain: "RWD",
    seatingCapacity: 2,
    price: 28550,
    color: "Soul Red Crystal",
    bodyStyle: "2-Door",
    mpgCity: 26,
    mpgHighway: 35,
  },
  {
    brand: "Subaru",
    model: "Outback",
    type: "Wagon",
    year: 2025,
    engine: "2.5L 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "CVT",
    horsepower: 182,
    torque: 176,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 32995,
    color: "Autumn Green Metallic",
    bodyStyle: "5-Door",
    mpgCity: 26,
    mpgHighway: 32,
  },
  {
    brand: "Subaru",
    model: "WRX",
    type: "Sedan",
    year: 2025,
    engine: "2.4L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Manual",
    horsepower: 271,
    torque: 258,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 31495,
    color: "WR Blue Pearl",
    bodyStyle: "4-Door",
    mpgCity: 21,
    mpgHighway: 29,
  },
  {
    brand: "Kia",
    model: "Telluride",
    type: "SUV",
    year: 2025,
    engine: "3.8L V6",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 291,
    torque: 262,
    drivetrain: "AWD",
    seatingCapacity: 8,
    price: 38990,
    color: "Everlasting Silver",
    bodyStyle: "5-Door",
    mpgCity: 20,
    mpgHighway: 26,
  },
  {
    brand: "Kia",
    model: "EV6",
    type: "Hatchback",
    year: 2025,
    engine: "Dual Motor Electric",
    fuelType: "Electric",
    transmission: "Automatic",
    horsepower: 320,
    torque: 446,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 47990,
    color: "Runway Red",
    bodyStyle: "5-Door",
    mpgCity: 116,
    mpgHighway: 0,
  },
  {
    brand: "Porsche",
    model: "911 Carrera",
    type: "Coupe",
    year: 2025,
    engine: "3.0L Twin-Turbo 6-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 379,
    torque: 331,
    drivetrain: "RWD",
    seatingCapacity: 4,
    price: 118900,
    color: "GT Silver Metallic",
    bodyStyle: "2-Door",
    mpgCity: 20,
    mpgHighway: 26,
  },
  {
    brand: "Porsche",
    model: "Cayenne",
    type: "SUV",
    year: 2025,
    engine: "3.0L Turbo V6",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 348,
    torque: 368,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 81950,
    color: "Carrara White",
    bodyStyle: "5-Door",
    mpgCity: 19,
    mpgHighway: 25,
  },
  {
    brand: "Volvo",
    model: "XC60",
    type: "SUV",
    year: 2025,
    engine: "2.0L Turbo 4-Cylinder",
    fuelType: "Hybrid",
    transmission: "Automatic",
    horsepower: 247,
    torque: 258,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 48900,
    color: "Crystal White",
    bodyStyle: "5-Door",
    mpgCity: 28,
    mpgHighway: 33,
  },
  {
    brand: "Volvo",
    model: "S60",
    type: "Sedan",
    year: 2025,
    engine: "2.0L Turbo 4-Cylinder",
    fuelType: "Hybrid",
    transmission: "Automatic",
    horsepower: 247,
    torque: 258,
    drivetrain: "FWD",
    seatingCapacity: 5,
    price: 42900,
    color: "Denim Blue",
    bodyStyle: "4-Door",
    mpgCity: 30,
    mpgHighway: 38,
  },
  {
    brand: "Lexus",
    model: "RX",
    type: "SUV",
    year: 2025,
    engine: "2.4L Turbo 4-Cylinder",
    fuelType: "Hybrid",
    transmission: "Automatic",
    horsepower: 246,
    torque: 233,
    drivetrain: "AWD",
    seatingCapacity: 5,
    price: 51990,
    color: "Eminent White Pearl",
    bodyStyle: "5-Door",
    mpgCity: 35,
    mpgHighway: 33,
  },
  {
    brand: "Lexus",
    model: "ES",
    type: "Sedan",
    year: 2025,
    engine: "2.5L 4-Cylinder",
    fuelType: "Hybrid",
    transmission: "CVT",
    horsepower: 215,
    torque: 163,
    drivetrain: "FWD",
    seatingCapacity: 5,
    price: 43990,
    color: "Ultra White",
    bodyStyle: "4-Door",
    mpgCity: 43,
    mpgHighway: 44,
  },
  {
    brand: "Jeep",
    model: "Grand Cherokee",
    type: "SUV",
    year: 2025,
    engine: "3.6L V6",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 293,
    torque: 260,
    drivetrain: "4WD",
    seatingCapacity: 5,
    price: 42990,
    color: "Diamond Black Crystal",
    bodyStyle: "5-Door",
    mpgCity: 19,
    mpgHighway: 26,
  },
  {
    brand: "Jeep",
    model: "Wrangler",
    type: "SUV",
    year: 2025,
    engine: "2.0L Turbo 4-Cylinder",
    fuelType: "Gasoline",
    transmission: "Automatic",
    horsepower: 270,
    torque: 295,
    drivetrain: "4WD",
    seatingCapacity: 5,
    price: 35990,
    color: "Sarge Green",
    bodyStyle: "2-Door",
    mpgCity: 22,
    mpgHighway: 25,
  },
];

// Generate image URL placeholder based on brand and model
export function getCarImageUrl(brand: string, model: string, year: number): string {
  const slug = `${brand}-${model}-${year}`.toLowerCase().replace(/\s+/g, "-");
  return `https://placehold.co/600x400/e2e8f0/475569?text=${encodeURIComponent(brand + " " + model)}`;
}
